# Python stubs generated by omniidl from idl/voicerecog.idl
# DO NOT EDIT THIS FILE!

import omniORB, _omnipy
from omniORB import CORBA, PortableServer
_0_CORBA = CORBA


_omnipy.checkVersion(4,2, __file__, 1)

try:
    property
except NameError:
    def property(*args):
        return None


#
# Start of module "Library"
#
__name__ = "Library"
_0_Library = omniORB.openModule("Library", r"idl/voicerecog.idl")
_0_Library__POA = omniORB.openModule("Library__POA", r"idl/voicerecog.idl")


# struct Dataset
_0_Library.Dataset = omniORB.newEmptyClass()
class Dataset (omniORB.StructBase):
    _NP_RepositoryId = "IDL:Library/Dataset:1.0"

    def __init__(self, state, recogdata, command, phase):
        self.state = state
        self.recogdata = recogdata
        self.command = command
        self.phase = phase

_0_Library.Dataset = Dataset
_0_Library._d_Dataset  = (omniORB.tcInternal.tv_struct, Dataset, Dataset._NP_RepositoryId, "Dataset", "state", (omniORB.tcInternal.tv_string,0), "recogdata", (omniORB.tcInternal.tv_wstring,0), "command", (omniORB.tcInternal.tv_string,0), "phase", (omniORB.tcInternal.tv_string,0))
_0_Library._tc_Dataset = omniORB.tcInternal.createTypeCode(_0_Library._d_Dataset)
omniORB.registerType(Dataset._NP_RepositoryId, _0_Library._d_Dataset, _0_Library._tc_Dataset)
del Dataset

# interface voicerecogdata
_0_Library._d_voicerecogdata = (omniORB.tcInternal.tv_objref, "IDL:Library/voicerecogdata:1.0", "voicerecogdata")
omniORB.typeMapping["IDL:Library/voicerecogdata:1.0"] = _0_Library._d_voicerecogdata
_0_Library.voicerecogdata = omniORB.newEmptyClass()
class voicerecogdata :
    _NP_RepositoryId = _0_Library._d_voicerecogdata[1]

    def __init__(self, *args, **kw):
        raise RuntimeError("Cannot construct objects of this type.")

    _nil = CORBA.Object._nil


_0_Library.voicerecogdata = voicerecogdata
_0_Library._tc_voicerecogdata = omniORB.tcInternal.createTypeCode(_0_Library._d_voicerecogdata)
omniORB.registerType(voicerecogdata._NP_RepositoryId, _0_Library._d_voicerecogdata, _0_Library._tc_voicerecogdata)

# voicerecogdata operations and attributes
voicerecogdata._d_setresult = (((omniORB.tcInternal.tv_string,0), ), (omniORB.typeMapping["IDL:Library/Dataset:1.0"], ), None)
voicerecogdata._d_voicerecog = ((omniORB.typeMapping["IDL:Library/Dataset:1.0"], ), (omniORB.typeMapping["IDL:Library/Dataset:1.0"], ), None)
voicerecogdata._d_voicerecogadditionalfunction = ((omniORB.typeMapping["IDL:Library/Dataset:1.0"], ), (omniORB.typeMapping["IDL:Library/Dataset:1.0"], ), None)

# voicerecogdata object reference
class _objref_voicerecogdata (CORBA.Object):
    _NP_RepositoryId = voicerecogdata._NP_RepositoryId

    def __init__(self, obj):
        CORBA.Object.__init__(self, obj)

    def setresult(self, *args):
        return self._obj.invoke("setresult", _0_Library.voicerecogdata._d_setresult, args)

    def voicerecog(self, *args):
        return self._obj.invoke("voicerecog", _0_Library.voicerecogdata._d_voicerecog, args)

    def voicerecogadditionalfunction(self, *args):
        return self._obj.invoke("voicerecogadditionalfunction", _0_Library.voicerecogdata._d_voicerecogadditionalfunction, args)

omniORB.registerObjref(voicerecogdata._NP_RepositoryId, _objref_voicerecogdata)
_0_Library._objref_voicerecogdata = _objref_voicerecogdata
del voicerecogdata, _objref_voicerecogdata

# voicerecogdata skeleton
__name__ = "Library__POA"
class voicerecogdata (PortableServer.Servant):
    _NP_RepositoryId = _0_Library.voicerecogdata._NP_RepositoryId


    _omni_op_d = {"setresult": _0_Library.voicerecogdata._d_setresult, "voicerecog": _0_Library.voicerecogdata._d_voicerecog, "voicerecogadditionalfunction": _0_Library.voicerecogdata._d_voicerecogadditionalfunction}

voicerecogdata._omni_skeleton = voicerecogdata
_0_Library__POA.voicerecogdata = voicerecogdata
omniORB.registerSkeleton(voicerecogdata._NP_RepositoryId, voicerecogdata)
del voicerecogdata
__name__ = "Library"

#
# End of module "Library"
#
__name__ = "voicerecog_idl"

_exported_modules = ( "Library", )

# The end.
