# DO NOT EDIT THIS FILE!
#
# Python module Library__POA generated by omniidl

import omniORB
omniORB.updateModule("Library__POA")

# ** 1. Stub files contributing to this module
import facedetection_idl

# ** 2. Sub-modules

# ** 3. End
